import React, { useState } from 'react';
import { useApp } from '../../context/AppContext';
import { Printer, X, Download, FileText, Database, Check } from 'lucide-react';

export const PDFExportModal: React.FC = () => {
  const { isPrintModalOpen, setIsPrintModalOpen, currentPatient, events } = useApp();
  const [downloadedFormat, setDownloadedFormat] = useState<string | null>(null);

  if (!isPrintModalOpen) return null;

  const patientEvents = events.filter(e => e.patientId === currentPatient.id);

  const triggerDownload = (filename: string, content: string, mimeType: string) => {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handleDownloadPDFText = () => {
    const textContent = `
===================================================================
PULSECARE AI CLINICAL HANDOFF BRIEF & PATIENT EHR SUMMARY
===================================================================
Date Generated: ${new Date().toLocaleDateString()}
MRN: ${currentPatient.mrn}
Patient Name: ${currentPatient.name}
Age / Gender: ${currentPatient.age}y / ${currentPatient.gender} (${currentPatient.bloodType})
Attending Physician: ${currentPatient.attendingPhysician}
Room Location: Ward 4 Bed 04

PRIMARY CLINICAL DIAGNOSIS:
- ${currentPatient.primaryDiagnosis}
- Overall Organ Risk Score: ${currentPatient.riskScore}/100 (${currentPatient.riskLevel.toUpperCase()})

DOCUMENTED ALLERGIES:
${currentPatient.allergies.map(a => `- ${a}`).join('\n')}

ACTIVE PHARMACOTHERAPY & MEDICATION HOLDS:
${currentPatient.activeMedications.map(m => `- ${m}`).join('\n')}

RECENT CLINICAL EVENTS & ANOMALY DELTA FLAGS:
${patientEvents.map(e => `[${e.timestamp}] ${e.title}: ${e.description}`).join('\n')}

Notice: Confidential Medical Document generated by PulseCare AI System.
===================================================================
    `.trim();

    triggerDownload(`EHR_Summary_${currentPatient.mrn}.txt`, textContent, 'text/plain');
    setDownloadedFormat('txt');
  };

  const handleDownloadCSV = () => {
    let csv = `Patient Name,MRN,Age,Gender,Blood Type,Diagnosis,Risk Score,Risk Level,Allergies,Active Medications\n`;
    csv += `"${currentPatient.name}","${currentPatient.mrn}",${currentPatient.age},"${currentPatient.gender}","${currentPatient.bloodType}","${currentPatient.primaryDiagnosis}",${currentPatient.riskScore},"${currentPatient.riskLevel}","${currentPatient.allergies.join('; ')}","${currentPatient.activeMedications.join('; ')}"\n\n`;
    csv += `Event Timestamp,Event Title,Description\n`;
    patientEvents.forEach(e => {
      csv += `"${e.timestamp}","${e.title}","${e.description}"\n`;
    });

    triggerDownload(`EHR_Lab_Dataset_${currentPatient.mrn}.csv`, csv, 'text/csv');
    setDownloadedFormat('csv');
  };

  const handleDownloadJSON = () => {
    const jsonContent = JSON.stringify({
      patient: currentPatient,
      clinicalEvents: patientEvents,
      exportedAt: new Date().toISOString(),
      systemVersion: "2.4-PulseCare-FastAPI"
    }, null, 2);

    triggerDownload(`EHR_Schema_${currentPatient.mrn}.json`, jsonContent, 'application/json');
    setDownloadedFormat('json');
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-md font-sans animate-fade-in">
      <div className="bg-[#0b1329] border border-cyan-500/30 rounded-3xl max-w-3xl w-full p-6 shadow-2xl space-y-6 max-h-[90vh] overflow-y-auto text-white">
        {/* Controls Header */}
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 border-b border-slate-800 pb-4 no-print">
          <div className="flex items-center gap-2">
            <Printer className="w-5 h-5 text-cyan-400" />
            <div>
              <h3 className="font-black text-slate-100 text-base">Export Patient Health Record & Clinical Brief</h3>
              <p className="text-xs text-slate-400 font-medium">Select your preferred export format for hospital handoff</p>
            </div>
          </div>
          <button
            onClick={() => setIsPrintModalOpen(false)}
            className="p-2 text-slate-400 hover:text-white bg-slate-800 rounded-xl cursor-pointer self-end sm:self-auto"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Export Formats Grid */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 no-print">
          <button
            onClick={handlePrint}
            className="p-3.5 rounded-2xl border border-cyan-500/40 bg-cyan-500/10 hover:bg-cyan-500/20 text-cyan-300 text-left space-y-1 cursor-pointer transition-all jiggle-hover"
          >
            <Printer className="w-5 h-5 text-cyan-400" />
            <div className="font-black text-xs">Print / PDF</div>
            <div className="text-[10px] text-slate-300">Browser print dialog</div>
          </button>

          <button
            onClick={handleDownloadPDFText}
            className="p-3.5 rounded-2xl border border-teal-500/40 bg-teal-500/10 hover:bg-teal-500/20 text-teal-300 text-left space-y-1 cursor-pointer transition-all jiggle-hover"
          >
            <FileText className="w-5 h-5 text-teal-400" />
            <div className="font-black text-xs">Text Clinical Brief</div>
            <div className="text-[10px] text-slate-300">Instant .txt file download</div>
          </button>

          <button
            onClick={handleDownloadCSV}
            className="p-3.5 rounded-2xl border border-amber-500/40 bg-amber-500/10 hover:bg-amber-500/20 text-amber-300 text-left space-y-1 cursor-pointer transition-all jiggle-hover"
          >
            <Download className="w-5 h-5 text-amber-400" />
            <div className="font-black text-xs">Excel / CSV Dataset</div>
            <div className="text-[10px] text-slate-300">Raw lab delta table</div>
          </button>

          <button
            onClick={handleDownloadJSON}
            className="p-3.5 rounded-2xl border border-purple-500/40 bg-purple-500/10 hover:bg-purple-500/20 text-purple-300 text-left space-y-1 cursor-pointer transition-all jiggle-hover"
          >
            <Database className="w-5 h-5 text-purple-400" />
            <div className="font-black text-xs">FastAPI JSON Schema</div>
            <div className="text-[10px] text-slate-300">RAG Vector EHR Object</div>
          </button>
        </div>

        {downloadedFormat && (
          <div className="p-3 rounded-xl bg-emerald-500/20 border border-emerald-500/40 text-emerald-300 text-xs font-black flex items-center gap-2 no-print">
            <Check className="w-4 h-4" /> Exported {downloadedFormat.toUpperCase()} file successfully to your downloads folder!
          </div>
        )}

        {/* Printable Preview Sheet */}
        <div className="p-6 bg-white text-slate-900 rounded-2xl space-y-6 border border-slate-300 print:border-none font-sans text-xs">
          <div className="border-b-2 border-slate-900 pb-4 flex justify-between items-start">
            <div>
              <h1 className="text-xl font-black tracking-tight text-slate-900">PULSECARE MEDICAL CENTER</h1>
              <p className="text-xs font-bold text-cyan-700">DEPARTMENT OF CLINICAL TELEMETRY & AI DECISION SUPPORT</p>
              <p className="text-[10px] text-slate-500">Nagpur Medical Health Hub • Cardiorenal Sepsis Project</p>
            </div>
            <div className="text-right">
              <div className="text-sm font-black text-slate-900">EXECUTIVE CLINICAL HANDOFF BRIEF</div>
              <div className="text-xs text-slate-600 font-mono">DATE: {new Date().toLocaleDateString()}</div>
              <div className="text-xs font-bold text-rose-600">CONFIDENTIAL MEDICAL RECORD</div>
            </div>
          </div>

          <div className="bg-slate-100 p-3 rounded-xl border border-slate-300 grid grid-cols-2 sm:grid-cols-4 gap-3 text-xs">
            <div>
              <span className="text-slate-500 font-bold uppercase text-[9px] block">Patient Name:</span>
              <strong className="text-slate-900 text-sm">{currentPatient.name}</strong>
            </div>
            <div>
              <span className="text-slate-500 font-bold uppercase text-[9px] block">MRN Number:</span>
              <strong className="text-slate-900">{currentPatient.mrn}</strong>
            </div>
            <div>
              <span className="text-slate-500 font-bold uppercase text-[9px] block">Age / Gender:</span>
              <strong className="text-slate-900">{currentPatient.age}y / {currentPatient.gender} ({currentPatient.bloodType})</strong>
            </div>
            <div>
              <span className="text-slate-500 font-bold uppercase text-[9px] block">Doctor / Room:</span>
              <strong className="text-slate-900">{currentPatient.attendingPhysician} (Ward 4 Bed 04)</strong>
            </div>
          </div>

          <div className="space-y-2">
            <div className="font-bold text-xs uppercase tracking-wider text-slate-700 border-b border-slate-300 pb-1">
              1. Primary Clinical Diagnosis & Organ Risk Profile
            </div>
            <p className="text-xs font-semibold text-slate-800">
              {currentPatient.primaryDiagnosis} — <span className="text-rose-600 font-black">Overall Organ Risk Score: {currentPatient.riskScore}/100 ({currentPatient.riskLevel.toUpperCase()})</span>
            </p>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div className="p-3 bg-rose-50 rounded-xl border border-rose-200">
              <strong className="text-rose-700 text-xs block mb-1">DOCUMENTED ALLERGIES:</strong>
              <ul className="list-disc pl-4 space-y-0.5 text-rose-950 font-semibold">
                {currentPatient.allergies.map((a, i) => (
                  <li key={i}>{a}</li>
                ))}
              </ul>
            </div>

            <div className="p-3 bg-cyan-50 rounded-xl border border-cyan-200">
              <strong className="text-cyan-800 text-xs block mb-1">ACTIVE PHARMACOTHERAPY & HOLDS:</strong>
              <ul className="list-disc pl-4 space-y-0.5 text-cyan-950 font-semibold">
                {currentPatient.activeMedications.map((m, i) => (
                  <li key={i}>{m}</li>
                ))}
              </ul>
            </div>
          </div>

          <div className="space-y-2">
            <div className="font-bold text-xs uppercase tracking-wider text-slate-700 border-b border-slate-300 pb-1">
              2. Key Longitudinal Events & AI Anomaly Delta Flags
            </div>
            <div className="space-y-2">
              {patientEvents.map(evt => (
                <div key={evt.id} className="p-2.5 bg-slate-50 border border-slate-200 rounded-xl">
                  <div className="flex justify-between font-bold text-slate-900 mb-1">
                    <span>{evt.title}</span>
                    <span className="text-slate-500 font-normal">{evt.timestamp}</span>
                  </div>
                  <p className="text-slate-700">{evt.description}</p>
                </div>
              ))}
            </div>
          </div>

          <div className="pt-8 border-t border-slate-300 flex justify-between items-end text-xs">
            <div>
              <p className="text-slate-500 italic">Generated automatically by PulseCare AI Decision Support System.</p>
            </div>
            <div className="text-right border-t border-slate-400 pt-2 w-48">
              <div className="font-bold text-slate-900">{currentPatient.attendingPhysician}</div>
              <div className="text-[10px] text-slate-500">Attending Physician Signature</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
